### ISSUE TITLE
Building fails on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by ohenley** [onox/orka#11]
I used GNAT 2017 GPL, clean sync on latest of both json-ada and orka : checkout master.

make build, along the way you should cross the following:

- json-ada is not recognized as a package (I did 'make install' for json-ada and I find these libs under /usr/gnat/lib. I do not know what is wrong) 

- orka-futures-slots.ads:56:21: internal call cannot appear in precondition of protected operation

- orka-loops.adb:21:06: file "orka-buffer_fences.ads" not found

- orka-loops.ads:63:41: internal call cannot appear in precondition of protected operation

Once fixed finally passed with many warnings though.

make examples:

- orka_test-test_2_two_triangles.adb:20:06: file "orka-buffers.ads" not found ... compilation of orka_test-test_1_triangle.adb failed ...

Once everything changed for Orka.Rendering.xyz most example builds. The execution of those binaries all leads to this:

Execution terminated by unhandled exception
raised PROGRAM_ERROR : gl-objects-renderbuffers.adb:144 access before elaboration
Call stack traceback locations:
0x7f8fab10ed8d 0x7f8fab1145a7 0x40a2de 0x4089e4 0x7f8fa9a07b95 0x408a18 0xfffffffffffffffe

In the light of those errors I propose you amend the Readme to let know the project is still in a WIP phase and might not build. Thx. 

p.s: see pull request with all the quick fixes to make it build.

**Comment by onox** [comment]
Did you set your `ADA_PROJECT_PATH` environment variable? It should point to a directory that contains `json_ada.gpr`. Executing `gnatls -v` should show the paths. How did you fix it eventually?

On Ubuntu you might want to use the GNAT FSF compiler instead with `sudo apt install gnat gprbuild`. I don't get the Program_Error you mentioned with GNAT FSF.

`Orka.Loops` and the glTF example are currently broken after implementing the job graph system. I'm currently working on sorting and batching of draw calls and finishing the glTF loader.

**Comment by ohenley** [comment]
No I did not set ADA_PROJECT_PATH. Thanks for the tip.

I hacked my way: 
'with "../json-ada/json_ada.gpr"' in orka.gpr and because of config.gpr conflicts (one in json-ada one in orka), I renamed the json-ada config.gpr to config_json_ada.gpr and baked the json-ada external 'variables' directly in the project file. It did the job but ... I know ... its brute force. :)

BTW, are you implementing something similar to what Tobias Persson presents here? http://ourmachinery.com/post/high-level-rendering-using-render-graphs/

Also to support gITF is awesome! 

Let me know when your project builds proper I really want to dig in/build on top a project of mine. IMO, it is of high importance to bring this type of project to Ada so people can build amazing stuff of very high quality.

Thank you and keep up the good work.

**Comment by onox** [comment]
> BTW, are you implementing something similar to what Tobias Persson presents here? http://ourmachinery.com/post/high-level-rendering-using-render-graphs/

Thanks for mentioning this. I wasn't aware of that blog post. What I'm trying to do now is that you're able to call OpenGL functions again. With the job graph system, there's a simulation loop and a render loop. The simulation loop will first execute a job that calls a "Fixed_Update" procedure of each "Behavior" object multiple times (for physics), then another job is executed which calls "Update" and "After_Update".

In the older code there's some parallelism but no job graph system. After "After_Update" I call a "Render" procedure which is used to do the actual rendering. Since the job graph system has been implemented, resources are loaded via jobs as well (so that some of the processing can be done in parallel). However, when a resource has been processed, it still needs to create some OpenGL buffers and upload its data. This can only be done in the render loop (the environment thread).

So I'm trying to find an efficient and flexible way to call OpenGL functions for creating buffers and doing draw calls. At the moment I'm trying [this](http://realtimecollisiondetection.net/blog/?p=86).

If you want to have a working revision of the project, you could reset to a commit where the job graph hasn't been enabled or implemented yet: https://github.com/onox/orka/commit/f5c5427a2ea7292bde091b7c72fc136ebcbea5ef or (even earlier) https://github.com/onox/orka/commit/8bd6a28ff9d831c58ee349644ad57c046fde826c.

One of those commits around that time should work with at least GNAT 7.2

If you want to export some Blender files to glTF you can use https://github.com/KhronosGroup/glTF-Blender-Exporter. The index type should be unsigned int (the glTF resource loader makes a bunch of assumptions at the moment). I can post some glTF files that should work if you need it.

**Comment by ohenley** [comment]
Thanks for the explanations.

Not exactly on point but have you read this:
https://software.intel.com/sites/default/files/Designing_a_Parallel_Game_Engine.pdf

Its presentation of structuring the synchronization of mixed "quantized"
jobs necessary for a real-time simulation is rather clear.

I will try the stable commits when time permits.

See you around.

**Comment by onox** [comment]
@ohenley GCC 8 and GNAT CE 2018 should now compile. So hopefully GNAT GPL 2017 should work too. See https://github.com/onox/orka/issues/10#issuecomment-413960913 On Ubuntu though, I still recommend to just use GNAT FSF 7.3.0.

**Comment by onox** [comment]
I'm going to close this issue since the project can be build with GCC 7.3 and 8.2. On Windows the project compiles with GNAT CE 2018 as well, so GNAT CE 2018 should compile on Linux as well.
