### ISSUE TITLE
Compilation fails on macOS with GNAT Community 2020

### ISSUE THREAD

**Issue by esthermations** [onox/orka#68]
<img width="990" alt="Screen Shot 2021-01-20 at 7 29 43 pm" src="https://user-images.githubusercontent.com/10289860/105151612-45226b80-5b5a-11eb-970c-37500ccb9021.png">

Let me know if you want any more relevant info, but this appears to be errors in the code rather than anything else.

Thank you!

**Comment by onox** [comment]
Hi Esther,

Hmm... the code compiles with GNAT FSF 7.5 and 10.2. Can you try to see if the code compiles if you replace the 3 occurrences of `'Access` with `'Unchecked_Access` in src/orka/implementation/orka-containers-bounded_vectors.adb? I don't have access to GNAT CE unfortunately.

The project could probably use some GitHub workflows that test building with various compilers and operating systems.

I have to mention though that Orka doesn't really support macOS (might not be clear from the README). If you take a look at https://orka-engine.netlify.app/installation/ you will see that there are a whole bunch of OpenGL 4.2 to 4.6 extensions that are required. A while ago Apple has deprecated their potato-quality 4.1 drivers in macOS and assumed the world would happily migrate to their proprietary Metal API. I hope to add a Vulkan backend in the future so that (in theory) it can run on macOS through MoltenVK.

**Comment by esthermations** [comment]
Ah, I didn't realise! Thanks for pointing that out.

Replacing with Unchecked_Access did fix the compilation but it then failed to link due to missing EGL functions, so I suppose that's that. Thanks very much for the help, in any case!
